apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fastapi-rolebinding
  namespace: fastapi-app
subjects:
  - kind: ServiceAccount
    name: fastapi-sa
    namespace: fastapi-app
roleRef:
  kind: Role
  name: fastapi-role
  apiGroup: rbac.authorization.k8s.io
