apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: YWRtaW4=
