{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-fastapi-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: fastapi
    release: {{ .Values.monitoring.serviceMonitor.prometheusRelease }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: fastapi
  endpoints:
  - port: {{ .Values.monitoring.serviceMonitor.portName }}
    path: {{ .Values.monitoring.serviceMonitor.path }}
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    {{- with .Values.monitoring.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
{{- end }}