apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: fastapi-app
spec:
  accessModes:
    - ReadWriteOnce   # Only one pod can mount this volume
  resources:
    requests:
      storage: 1Gi