apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: fastapi-app
spec:
  type: ClusterIP   # Internal only, not exposed outside cluster
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
